## 1. Archive exploration

Take some time to look through the dataset’s description in EDI and click around. Then click on View Full Metadata, go to the “Detailed Metadata” section and click on “Data Entities” to look at the descriptions for the dataset’s columns.

Use the dataset’s description and the metadata to answer the following questions:

Who assembled this data, and why?
What does a single row in the data represent?
When and where were the observations collected?
Does the dataset contain sensitive data?
What study protocols were used to collect the data?
What are the units for the hares’ weight?
Does the metadata say how missing data is encoded?
Is there a publication associated with this dataset?
In your notebook: use a markdown cell to briefly answer these questions. Include as well a citation, date of access, and a link to the archive.

Before you look at the data itself, think about what you learned about how this data was collected. In a markdown cell, write down two or three questions about possible issues you might find in the data.

Do not skip the archive exploration! Understanding your data provenance is a crucial part of the analysis

## 2. Adding an image

![bunny photo](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/1920px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

## 3. Data loading and preliminary exploration

Back in your notebook, import the 55_Hare_Data_2012.txt file available here. Store it in a variable named hares.

Using pandas methods, obtain preliminary information and explore this data frame. Consider answering some of these questions:

What are the dimensions of the data frame and what are the data types of the columns? Do the data types match what you would expect from each column?
Are there any columns that have a significant number of NA values?
What are the minimum and maximum values for the weight and hind feet measurements?
What are the unique values for some of the categorical columns?
Did any of the issues you anticipated in 1c show up?

In [2]:
import pandas as pd
import numpy as np

hares = pd.read_csv("data/55_Hare_Data_2012.txt")

In [3]:
# View first few rows
hares.head()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population
3,11/26/1998,NaN,bonrip,2E,414D262D43,NaN,NaN,NaN,1490.0,135.0,NaN,931.0,51,Population
4,11/26/1998,NaN,bonrip,3B,414D2B4B58,NaN,NaN,NaN,1710.0,150.0,NaN,933.0,51,Population

In [11]:
# Check dimensions
hares.shape

(3380, 14)

In [12]:
# Column types and non-null counts
hares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [13]:
# Missing values per column
hares.isna()

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,False,True,False,False,False,True,True,True,False,False,True,False,False,False
1,False,True,False,False,False,True,False,True,False,True,True,False,False,False
2,False,True,False,False,False,True,False,True,False,True,True,False,False,False
3,False,True,False,False,False,True,True,True,False,False,True,False,False,False
4,False,True,False,False,False,True,True,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3375,False,False,False,False,False,False,True,True,False,True,True,False,False,False
3376,False,False,False,False,False,False,True,True,True,True,True,False,False,False
3377,False,True,False,False,False,False,True,True,False,False,True,False,False,False
3378,False,True,False,False,False,False,True,True,False,True,True,False,False,False
3379,False,True,False,False,False,False,False,True,False,False,True,False,False,False

In [16]:
# Sums all of boolean columns
hares.isna().sum()

date             0
time          3116
grid             0
trap            12
l_ear           48
r_ear          169
sex            352
age           2111
weight         535
hindft        1747
notes         3137
b_key           47
session_id       0
study          163
dtype: int64

In [17]:
# How many rows vs unique hares?
print(hares.shape[0], hares['l_ear'].nunique())

# Details: hares.shape[0] returns the number of rows in the DataFrame - the total count of capture events
# hares['l_ear'].unique(())

3380 1020

In [23]:
# Recapture the distrubution (how many values exist for each of the hare we have)
hares.groupby('l_ear').size()

# Define into a variable
captures_per_hare = hares.groupby('l_ear').size()

captures_per_hare.describe()

count    1020.000000
mean        3.266667
std         4.051371
min         1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max        42.000000
dtype: float64

In [25]:
# Min and max for continuous measurements
print("Weight (g):", hares['weight'].min(), "", hares['weight'].max())

Weight (g): 0.0  2365.0

In [28]:
# Unique values for key categorical columns
print("grid:", hares['grid'].unique())
print("age:", hares['age'].unique())
print("study:", hares['study'].unique())
print("sex:", hares['sex'].unique())

grid: ['bonrip' 'bonbs' 'Bonbs' 'bonmat' 'bonmat ']
age: [nan 'J' 'A' 'a 1 yr.' 'a 3/4 yr.' 'a 1 yr' '1 yr' '1 yr.' '2 yrs.'
 '2 yrs' 'a 2 yrs.' '2.25 yrs' '3.5 yrs.' '3 yrs.' '2.5 yrs' '3.25 yrs.'
 'A 1.5' '?' 'U' 'j' 'a' 'u' 'J 3/4' 'A 3/4' 'A 1/2' '3/4/2013' '1/4/2013'
 '1/2/2013' '1' '1.25' '1.5']
study: ['Population' 'Collar' nan 'Metabolic' 'Metabolic/Collar']
sex: [nan 'M' 'F' '?' 'F?' 'M?' 'pf' 'm' 'f' 'f?' 'm?' 'f ' 'm ']